name: Daily Game Cleanup Check

on:
  schedule:
    - cron: "0 9 * * *" # executa todo dia Ã s 09:00 UTC
  workflow_dispatch:

jobs:
  check-games:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create minimal service-account.json
        run: |
          echo "${{ secrets.FIREBASE_PRIVATE_KEY }}" | sed 's/\\n/\n/g' > key.txt
          cat <<EOF > service-account.json
          {
            "type": "service_account",
            "project_id": "${{ secrets.FIREBASE_PROJECT_ID }}",
            "private_key": "$(cat key.txt)",
            "client_email": "${{ secrets.FIREBASE_CLIENT_EMAIL }}"
          }
          EOF

      - name: Run scheduled script
        run: node .github/scripts/checkGames.js
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_SERVER_KEY: ${{ secrets.FIREBASE_SERVER_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
